services:
  ifound_docker:
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    #env_file is  Docker Compose CLI feature, so you can't use with out compose 
    env_file:
      - .env
    ports: 
      - "${PORT}:${PORT}"

    depends_on:
      - mongodb
    command: node dist/index.js

  mongodb:
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASSWORD}
    volumes:
        - MONGO_VOLUMES:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGOUSERNAME}:${MONGOPASSWORD}@localhost:27017 --quiet
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "27017:27017"
volumes:
  MONGO_VOLUMES:
