services:

  #This for the local dev usecase, When it deploy,
  #We connect to mongodb atlas.
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASSWORD}
    volumes:
        - MONGO_VOLUMES:/data/db
    ports:
      - "27017:27017"

volumes:
  MONGO_VOLUMES:
